### ISSUE TITLE
Numerous invalid `NoneType()` comparisons when comparing temperatures

### ISSUE THREAD

**Issue by alexander-bauer** [umbc-hackafe/idiotic#27]
```
TypeError: unorderable types: float() < NoneType()
INFO:idiotic.item:Number 'Entertainment Room Humidity' changed state from 53.099998 -> 53.200001
ERROR:idiotic.dispatch:Error while running functools.partial(<function temp_change at 0x7fb81460c6a8>, StateChangeEvent(after, None -> 19.833333333333332 on Group 'Average Temperature' from group_member,module.http)) from dispatch queue:
Traceback (most recent call last):
  File "/home/sasha/dev/python/idiotic/idiotic/dispatch.py", line 38, in run
    res = yield from coroutine(func)()
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "idiotic-config/rules/climate.py", line 31, in temp_change
    if current < c.items.minimum_temperature.state:
TypeError: unorderable types: float() < NoneType()
```

This probably produces the desired effect, but the log message looks scary.

**Comment by dylwhich** [comment]
This is actually an issue in idiotic-config

**Comment by alexander-bauer** [comment]
Moved to https://github.com/umbc-hackafe/idiotic-config/issues/3.
