### ISSUE TITLE
State change in Scene from API causes AttributeError

### ISSUE THREAD

**Issue by alexander-bauer** [umbc-hackafe/idiotic#28]
When trying to _change_ the state of any scene from the API, _a la_ `/api/scene/party/command/enter` if its current activity is false, the following error is raised.

```
ERROR:idiotic.utils.api:Exception encountered from API, args=(), kwargs={'command': 'enter', 'name': 'party'}
Traceback (most recent call last):
  File "idiotic-config/modules/_api.py", line 29, in scene_command
    elif command == "exit":
  File "/home/sasha/dev/python/idiotic/idiotic/scene.py", line 98, in enter
    return self._switch(True)
  File "/home/sasha/dev/python/idiotic/idiotic/scene.py", line 29, in _switch
    idiotic.dispatcher.dispatch(pre_event)
AttributeError: module 'idiotic' has no attribute 'dispatcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sasha/dev/python/idiotic/idiotic/utils/api.py", line 12, in decorator
    res = func(*args, **kwargs)
  File "idiotic-config/modules/_api.py", line 36, in scene_command
ValueError: Scene 'party' does not exist!
```

This presents as a `ValueError`, but that is itself caused by the previous `AttributeError: module 'idiotic' has no attribute 'dispatcher'`.

This occurs from line 29 in idiotic/scene.py

```
    idiotic.dispatcher.dispatch(pre_event)
```

which, as far as I can figure, results from a missing or disorganized import.

**Comment by alexander-bauer** [comment]
@dylwhich Please have a look when you can
