### ISSUE TITLE
Failed module loads cause non-obvious errors

### ISSUE THREAD

**Issue by alexander-bauer** [umbc-hackafe/idiotic#45]
Because `persistence` is a default module, its requirements should probably be included in setup.py, but if they arenot, then it yields

```
INFO:idiotic.main:Connecting to persistence engine...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sasha/dev/python/idiotic/idiotic/__main__.py", line 203, in <module>
    main()
  File "/home/sasha/dev/python/idiotic/idiotic/__main__.py", line 182, in main
    instance = init()
  File "/home/sasha/dev/python/idiotic/idiotic/__main__.py", line 155, in init
    instance._start_persistence(config["persistence"]["method"], config["persistence"])
  File "/home/sasha/dev/python/idiotic/idiotic/__init__.py", line 198, in _start_persistence
    persist_cls = persist_types[persist]
KeyError: 'sql'
```

This is solved by installing `sqlalchemy`, but should be amended to yield a omre informative error message.

**Comment by dylwhich** [comment]
Editing this to accomodate another similar issue. When a module cannot be loaded as a directory (e.g. **init**.py does not exist), a very strange error occurs - for some reason the modules dictionary ceases to exist.

```
INFO:idiotic.utils:Attempting to load directory etc/modules/webui as a module...
ERROR:idiotic.utils:Unable to load module etc/modules/webui: etc/modules/webui/__init__.py does not exist

...

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dylan/dev/idiotic/idiotic/__main__.py", line 204, in <module>
    main()
  File "/home/dylan/dev/idiotic/idiotic/__main__.py", line 182, in main
    instance = init()
  File "/home/dylan/dev/idiotic/idiotic/__main__.py", line 113, in init
    ignore=instance.modules):
TypeError: 'NoneType' object is not iterable
```

**Comment by dylwhich** [comment]
Failure to load a module should probably be considered fatal.
